[phases.setup]
nixPkgs = ["python3Full"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements-railway.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
